import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/shared/providers/auth-provider";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
// import {Clicker_Script} from "next/font/google";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const clickerScript = Clicker_Script({
//   variable: "--font-clicker-script",
//   weight: "400",
// });

const clickerScript = localFont({
  src: '../public/fonts/Clicker_Script/ClickerScript-Regular.ttf',
  variable: "--font-clicker-script",
  weight: "400",
})

export const metadata: Metadata = {
  title: "EV-b",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${clickerScript.variable} ${clickerScript.className} h-full antialiased`}
    >
      <body className="min-h-full bg-[radial-gradient(ellipse_at_center,#EBF3F5_19%,#98CBD7_100%)] font-sans antialiased">
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
